### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [araraloren/Net-FTPlib#5]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/araraloren/Net-FTP
- https://github.com/araraloren/Net-FTPlib
- https://github.com/araraloren/perl6-app-snippet

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by araraloren** [comment]
Hi, what need I do? It would be nice if these module can help anyone.

**Comment by lizmat** [comment]
I've sent you an invite for raku-community-modules.  After accepting that, you will be able to transfer these repos to it.  After that, someone (probably me) will take care of moving these modules to the zef ecosystem.

**Comment by araraloren** [comment]
Okay, please.

> I've sent you an invite for raku-community-modules. After accepting that, you will be able to transfer these repos to it. After that, someone (probably me) will take care of moving these modules to the zef ecosystem.

**Comment by lizmat** [comment]
Thanks for the transfer!
